title:          L154 Gaming
description:    "Stop bermain judi slot. Mainkan permainan slot demo gratis tanpa deposit atau memakai uang asli."
baseurl:        "/"
url:            "https://l154gamer.github.io/"
markdown: kramdown
future: true
encoding: UTF-8
locales: ["id", "en"]
language_default: id
include:
  - _pages

collections:
  id:
    output: true
    permalink: /:collection/:slug
  en:
    output: true
    permalink: /:collection/:slug

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "id"
    values:
      layout: "page"
      locale: id
  -
    scope:
      path: ""
      type: "en"
    values:
      layout: "page"
      locale: en

