title:          L154
description:    "Stop bermain judi slot. Mainkan saja permainan slot demo gratis tanpa deposit atau memakai uang asli."
baseurl:        "/"
url:            "https://l154gamer.github.io/"
markdown: kramdown
future: true
encoding: UTF-8
include:
  - _pages
  - _posts
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: post
      permalink: /news/:title
  - scope:
      path: "_pages"
      type: "pages"
